"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[line_break]
disabled = true

format = """$directory\
$git_branch\
$git_commit\
$git_status\
$docker_context\
$line_break$character"""

[character] 
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:yellow)'
vimcmd_replace_symbol = '[](bold fg:green)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

[aws]
symbol = " aws"
disabled = true

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[directory]
style = "bold fg:blue"
truncation_length= 1
truncate_to_repo = true
format = "[ $path ]($style)"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 Documents"
"Downloads" = " Downloads"
"Music" = "󰝚 Music"
"Pictures" = " Pictures"
"things" = "󰲋 things"

[docker_context]
symbol = " "
format = ' [$symbol](blue bold)'
disabled = false

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
style = "bold green" 
symbol = " "
format = 'on [$symbol$branch(:$remote_branch)]($style) '

[git_commit]
style = "green" 
tag_symbol = '  '
format = '[\($hash$tag\)]($style) '

[git_status]
style = "green" 
format = '([\[$all_status$ahead_behind\]]($style) )'

[golang]
symbol = " "
disabled = true

[guix_shell]
symbol = " "
disabled = true

[haskell]
symbol = " "
disabled = true

[haxe]
symbol = " "
disabled = true

[hg_branch]
symbol = " "
disabled = true

[hostname]
ssh_symbol = " "
disabled = true

[java]
symbol = " "
disabled = true

[julia]
symbol = " "
disabled = true

[kotlin]
symbol = " "
disabled = true

[lua]
#ymbol = " "
disabled = true

[memory_usage]
symbol = "󰍛 "
disabled = true

[meson]
symbol = "󰔷 "
disabled = true

[nim]
symbol = " "
disabled = true

[nodejs]
symbol = " "
#format = 'via [$symbol]($style)'
disabled = true

[ocaml]
symbol = " "
disabled = true

[perl]
symbol = " "
disabled = true

[php]
symbol = " "
disabled = true

[pijul_channel]
symbol = " "
disabled = true

[python]
symbol = " "
disabled = true

[rlang]
symbol = "󰟔 "
disabled = true

[ruby]
symbol = " "
disabled = true

[rust]
symbol = "󱘗 "
disabled = true

[scala]
symbol = " "
disabled = true

[swift]
symbol = " "
disabled = true

[zig]
symbol = " "
disabled = true

[gradle]
symbol = " "
disabled = true

[dotnet]
style = "purple"
disabled = true

[cmd_duration]
disabled = true

[package]
disabled = true
