general.import = [
  "~/.config/alacritty/theme.toml"
]

[font]
size = 14
builtin_box_drawing = false

[font.bold]
family = "CaskaydiaCove NFM" 
style = "SemiBold"

[font.bold_italic]
family = "CaskaydiaCove NFM"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove NFM"
style = "Italic"

[font.normal]
family = "CaskaydiaCove NFM"
style = "Regular"

[[hints.enabled]]
regex = "[^ ]+\\.rs:\\d+:\\d+"
command = { program = "code", args = [ "--goto" ] }
mouse = { enabled = true }

[window]
padding = {x = 20, y = 20}
dynamic_padding = true
decorations = "None"
opacity = 1

[mouse]
hide_when_typing = false

[cursor]
style = { shape = "Block", blinking = "Never" }   # block cursor, no blinking
vi_mode_style = "Block"                           # use block for vi mode too
blink_interval = 750
blink_timeout = 0                                 # never stop blinking (optional)
unfocused_hollow = false                          # solid block when unfocused
thickness = 1.0                                   # full width of the cell
